apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2023-10-18T06:40:27Z","generation":2,"labels":{"app":"gke-sample"},"name":"gke-sample","namespace":"default","resourceVersion":"3504388","uid":"342e3708-1345-40c7-a585-9aa6b7ffd610"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"gke-sample"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"gke-sample"}},"spec":{"containers":[{"image":"asia-east1-docker.pkg.dev/projectb-400301/gcp-poc/gke-sample@sha256:b3e5e34861461948819c7a54bb52525aece62d19f4b90fa250eff34da16e3091","imagePullPolicy":"IfNotPresent","name":"gke-sample-sha256-1","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"my-java-app-sa","serviceAccountName":"my-java-app-sa","terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2023-10-18T06:40:59Z","lastUpdateTime":"2023-10-18T06:40:59Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2023-10-18T06:40:29Z","lastUpdateTime":"2023-10-18T06:52:28Z","message":"ReplicaSet \"gke-sample-84544db75c\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":2,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2023-10-18T06:40:27Z"
  generation: 3
  labels:
    app: gke-sample
  name: gke-sample
  namespace: default
  resourceVersion: "4009662"
  uid: 342e3708-1345-40c7-a585-9aa6b7ffd610
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gke-sample
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gke-sample
    spec:
      containers:
        - image: asia-east1-docker.pkg.dev/projectb-400301/gcp-poc/gke-sample@sha256:b3e5e34861461948819c7a54bb52525aece62d19f4b90fa250eff34da16e3091
          imagePullPolicy: IfNotPresent
          name: gke-sample-sha256-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: my-java-app-sa
      serviceAccountName: my-java-app-sa
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
    - lastTransitionTime: "2023-10-18T06:40:59Z"
      lastUpdateTime: "2023-10-18T06:40:59Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-10-18T06:40:29Z"
      lastUpdateTime: "2023-10-18T06:52:28Z"
      message: ReplicaSet "gke-sample-84544db75c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/neg":"{\"ingress\":true}"},"creationTimestamp":"2023-10-18T06:41:04Z","finalizers":["service.kubernetes.io/load-balancer-cleanup"],"labels":{"app":"gke-sample"},"name":"gke-sample-service","namespace":"default","resourceVersion":"3499321","uid":"95183e82-86fd-4521-a888-97416589efbd"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"10.68.14.81","clusterIPs":["10.68.14.81"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":30171,"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"gke-sample"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"ip":"35.201.183.205"}]}}}
  creationTimestamp: "2023-10-18T06:41:04Z"
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: gke-sample
  name: gke-sample-service
  namespace: default
  resourceVersion: "4007850"
  uid: 95183e82-86fd-4521-a888-97416589efbd
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.68.14.81
  clusterIPs:
    - 10.68.14.81
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30171
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: gke-sample
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 35.201.183.205
